/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.ujaen.tfg.vistas;

import com.mxrck.autocompleter.TextAutoCompleter;
import es.ujaen.tfg.modelo.Local;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jota
 */
public class VistaCrearFactura extends javax.swing.JFrame {

    private TextAutoCompleter autoCompleterBuscadorClientes;
    private TextAutoCompleter autoCompleterBuscadorLocales;

    private Local local = new Local("1", "Calle Campanas", "Panadería Ramoni", 300.0);

    /**
     * Creates new form VistaCrearFactura
     */
    public VistaCrearFactura() {
        initComponents();

        cargarAutocompletarBuscadorClientes();
        cargarAutocompletarBuscadorLocales();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroupFactura = new javax.swing.ButtonGroup();
        jPanelPrincipal = new javax.swing.JPanel();
        jPanelDetallesFactura = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelBuscarCliente = new javax.swing.JLabel();
        jTextFieldBuscadorClientes = new javax.swing.JTextField();
        jLabelFechaFactura = new javax.swing.JLabel();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jLabelElegirTipoFactura = new javax.swing.JLabel();
        jPanelRadioButtons = new javax.swing.JPanel();
        jRadioButtonFactura = new javax.swing.JRadioButton();
        jRadioButtonFacturaAbono = new javax.swing.JRadioButton();
        jPanelCuerpo = new javax.swing.JPanel();
        jPanelTitulo = new javax.swing.JPanel();
        jLabelSeleccionarLocal = new javax.swing.JLabel();
        jPanelSeleccionarLocal = new javax.swing.JPanel();
        jLabelBuscarLocal = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        jLabelPrecioUnitario = new javax.swing.JLabel();
        jLabelIVA = new javax.swing.JLabel();
        jLabelRetencion = new javax.swing.JLabel();
        jTextFieldBuscadorLocales = new javax.swing.JTextField();
        jSpinnerCantidad = new javax.swing.JSpinner();
        jLabelPrecioUnitarioValor = new javax.swing.JLabel();
        jLabelIVAValor = new javax.swing.JLabel();
        jLabelRetencionValor = new javax.swing.JLabel();
        jPanelBotonAgregarLocal = new javax.swing.JPanel();
        jButtonAgregarLocal = new javax.swing.JButton();
        jButtonEliminarLocal = new javax.swing.JButton();
        jScrollPaneTabla = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanelPiePagina = new javax.swing.JPanel();
        jPanelLabelTotal = new javax.swing.JPanel();
        jLabelTotal = new javax.swing.JLabel();
        jPanelBotones = new javax.swing.JPanel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonGenerarFactura = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear Factura");
        setLocationByPlatform(true);

        jPanelPrincipal.setLayout(new java.awt.BorderLayout());

        jPanelDetallesFactura.setLayout(new java.awt.GridBagLayout());

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitulo.setText("Crear Factura");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelDetallesFactura.add(jLabelTitulo, gridBagConstraints);

        jLabelBuscarCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelBuscarCliente.setText("Buscar Cliente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelDetallesFactura.add(jLabelBuscarCliente, gridBagConstraints);

        jTextFieldBuscadorClientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldBuscadorClientes.setMinimumSize(new java.awt.Dimension(125, 26));
        jTextFieldBuscadorClientes.setPreferredSize(new java.awt.Dimension(125, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 58;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelDetallesFactura.add(jTextFieldBuscadorClientes, gridBagConstraints);

        jLabelFechaFactura.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelFechaFactura.setText("Fecha de Factura");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 25.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelDetallesFactura.add(jLabelFechaFactura, gridBagConstraints);

        jDateChooser.setDateFormatString("dd/MM/yyyy");
        jDateChooser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jDateChooser.setPreferredSize(new java.awt.Dimension(103, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 25.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelDetallesFactura.add(jDateChooser, gridBagConstraints);

        jLabelElegirTipoFactura.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelElegirTipoFactura.setText("Elegir Tipo de Factura");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelDetallesFactura.add(jLabelElegirTipoFactura, gridBagConstraints);

        buttonGroupFactura.add(jRadioButtonFactura);
        jRadioButtonFactura.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButtonFactura.setText("Factura");
        jPanelRadioButtons.add(jRadioButtonFactura);

        buttonGroupFactura.add(jRadioButtonFacturaAbono);
        jRadioButtonFacturaAbono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButtonFacturaAbono.setText("Factura de Abono");
        jPanelRadioButtons.add(jRadioButtonFacturaAbono);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 25.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelDetallesFactura.add(jPanelRadioButtons, gridBagConstraints);

        jPanelPrincipal.add(jPanelDetallesFactura, java.awt.BorderLayout.NORTH);

        jPanelCuerpo.setLayout(new javax.swing.BoxLayout(jPanelCuerpo, javax.swing.BoxLayout.Y_AXIS));

        jPanelTitulo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabelSeleccionarLocal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelSeleccionarLocal.setText("Seleccionar Local");
        jLabelSeleccionarLocal.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanelTitulo.add(jLabelSeleccionarLocal);

        jPanelCuerpo.add(jPanelTitulo);

        jPanelSeleccionarLocal.setLayout(new java.awt.GridBagLayout());

        jLabelBuscarLocal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelBuscarLocal.setText("Buscar Local");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 0);
        jPanelSeleccionarLocal.add(jLabelBuscarLocal, gridBagConstraints);

        jLabelCantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCantidad.setText("Cantidad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 25, 2, 0);
        jPanelSeleccionarLocal.add(jLabelCantidad, gridBagConstraints);

        jLabelPrecioUnitario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPrecioUnitario.setText("Precio Unitario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 25, 2, 0);
        jPanelSeleccionarLocal.add(jLabelPrecioUnitario, gridBagConstraints);

        jLabelIVA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelIVA.setText("IVA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 25, 2, 0);
        jPanelSeleccionarLocal.add(jLabelIVA, gridBagConstraints);

        jLabelRetencion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelRetencion.setText("Retención");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 25, 2, 0);
        jPanelSeleccionarLocal.add(jLabelRetencion, gridBagConstraints);

        jTextFieldBuscadorLocales.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldBuscadorLocales.setPreferredSize(new java.awt.Dimension(180, 26));
        jTextFieldBuscadorLocales.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldBuscadorLocalesFocusLost(evt);
            }
        });
        jTextFieldBuscadorLocales.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBuscadorLocalesKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 0);
        jPanelSeleccionarLocal.add(jTextFieldBuscadorLocales, gridBagConstraints);

        jSpinnerCantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jSpinnerCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 0, null, 1));
        jSpinnerCantidad.setPreferredSize(new java.awt.Dimension(75, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 25, 2, 0);
        jPanelSeleccionarLocal.add(jSpinnerCantidad, gridBagConstraints);

        jLabelPrecioUnitarioValor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 25, 2, 0);
        jPanelSeleccionarLocal.add(jLabelPrecioUnitarioValor, gridBagConstraints);

        jLabelIVAValor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelIVAValor.setText("21 %");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 25, 2, 0);
        jPanelSeleccionarLocal.add(jLabelIVAValor, gridBagConstraints);

        jLabelRetencionValor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelRetencionValor.setText("19 %");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 25, 2, 0);
        jPanelSeleccionarLocal.add(jLabelRetencionValor, gridBagConstraints);

        jPanelCuerpo.add(jPanelSeleccionarLocal);

        jPanelBotonAgregarLocal.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButtonAgregarLocal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonAgregarLocal.setText("Agregar Local");
        jButtonAgregarLocal.setNextFocusableComponent(jButtonCancelar);
        jButtonAgregarLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarLocalActionPerformed(evt);
            }
        });
        jPanelBotonAgregarLocal.add(jButtonAgregarLocal);

        jButtonEliminarLocal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonEliminarLocal.setText("Eliminar Local");
        jButtonEliminarLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarLocalActionPerformed(evt);
            }
        });
        jPanelBotonAgregarLocal.add(jButtonEliminarLocal);

        jPanelCuerpo.add(jPanelBotonAgregarLocal);

        jTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Local", "Precio Unitario", "IVA", "Retención", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.setShowGrid(false);
        jTable.getTableHeader().setReorderingAllowed(false);
        jScrollPaneTabla.setViewportView(jTable);
        if (jTable.getColumnModel().getColumnCount() > 0) {
            jTable.getColumnModel().getColumn(0).setPreferredWidth(5);
            jTable.getColumnModel().getColumn(2).setPreferredWidth(15);
            jTable.getColumnModel().getColumn(3).setPreferredWidth(10);
            jTable.getColumnModel().getColumn(4).setPreferredWidth(10);
        }

        jPanelCuerpo.add(jScrollPaneTabla);

        jPanelPrincipal.add(jPanelCuerpo, java.awt.BorderLayout.CENTER);

        jPanelPiePagina.setName(""); // NOI18N
        jPanelPiePagina.setLayout(new java.awt.GridLayout(1, 2));

        jLabelTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTotal.setText("Total: 0,00€");
        jPanelLabelTotal.add(jLabelTotal);

        jPanelPiePagina.add(jPanelLabelTotal);

        jPanelBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanelBotones.add(jButtonCancelar);

        jButtonGenerarFactura.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonGenerarFactura.setText("Generar Factura");
        jButtonGenerarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarFacturaActionPerformed(evt);
            }
        });
        jPanelBotones.add(jButtonGenerarFactura);

        jPanelPiePagina.add(jPanelBotones);

        jPanelPrincipal.add(jPanelPiePagina, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonGenerarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarFacturaActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonGenerarFacturaActionPerformed

    private void jTextFieldBuscadorLocalesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscadorLocalesKeyReleased
        // TODO add your handling code here:
        //Cada vez que soltamos la tecla en el buscador, se actualiza el valor del precio
        actualizarLabelPrecioUnitarioValor();
    }//GEN-LAST:event_jTextFieldBuscadorLocalesKeyReleased

    private void jTextFieldBuscadorLocalesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBuscadorLocalesFocusLost
        // TODO add your handling code here:
        //Cada vez que perdemos el enfoque del buscador, se actualiza el valor del precio
        actualizarLabelPrecioUnitarioValor();
    }//GEN-LAST:event_jTextFieldBuscadorLocalesFocusLost

    private void jButtonAgregarLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarLocalActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) jTable.getModel();

        modelo.addRow(new Object[]{jSpinnerCantidad.getValue(), local.getArticulo(), local.getPrecio(), 21.0, 19.0});

        calcularTotal();
    }//GEN-LAST:event_jButtonAgregarLocalActionPerformed

    private void jButtonEliminarLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarLocalActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) jTable.getModel();
        
        modelo.removeRow(jTable.getSelectedRow());

        calcularTotal();
    }//GEN-LAST:event_jButtonEliminarLocalActionPerformed

    private void cargarAutocompletarBuscadorClientes() {
        //Iniciamos el Autocompletes con el Buscador de Clientes
        autoCompleterBuscadorClientes = new TextAutoCompleter(jTextFieldBuscadorClientes);

        //Esto hace que también se pueda buscar por en medio del String
        autoCompleterBuscadorClientes.setMode(0);

        //Añadimos las palabras clave (opciones) al Autocompleter
        autoCompleterBuscadorClientes.addItem("Ramoni");
        autoCompleterBuscadorClientes.addItem("Juani");
        autoCompleterBuscadorClientes.addItem("Juana");
        autoCompleterBuscadorClientes.addItem("Ramona");
    }

    private void cargarAutocompletarBuscadorLocales() {
        //Iniciamos el Autocompletes con el Buscador de Clientes
        autoCompleterBuscadorLocales = new TextAutoCompleter(jTextFieldBuscadorLocales);

        //Esto hace que también se pueda buscar por en medio del String
        autoCompleterBuscadorLocales.setMode(0);

        //Añadimos las palabras clave (opciones) al Autocompleter
        autoCompleterBuscadorLocales.addItem(local.getArticulo());
        autoCompleterBuscadorLocales.addItem(local.getAlias());
    }

    private void actualizarLabelPrecioUnitarioValor() {
        if (jTextFieldBuscadorLocales.getText().equals(local.getAlias())
                || jTextFieldBuscadorLocales.getText().equals(local.getArticulo())) {
            jLabelPrecioUnitarioValor.setText(local.getPrecio() + " €");
        } else {
            jLabelPrecioUnitarioValor.setText("");
        }
    }

    private void calcularTotal() {
        DefaultTableModel modelo = (DefaultTableModel) jTable.getModel();
        double total = 0;
        for (int i = 0; i < modelo.getRowCount(); i++) {
            int cantidad = Integer.parseInt(modelo.getValueAt(i, 0).toString());
            double precio = Double.parseDouble(modelo.getValueAt(i, 2).toString());
            double iva = Double.parseDouble(modelo.getValueAt(i, 3).toString());
            double retencion = Double.parseDouble(modelo.getValueAt(i, 4).toString());
            double subtotal = cantidad * precio * (1 + iva / 100) * (1 - retencion / 100);
            modelo.setValueAt(subtotal, i, 5);
            total += subtotal;
        }
        jLabelTotal.setText("Total: " + String.format("%.2f", total) + " €");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupFactura;
    private javax.swing.JButton jButtonAgregarLocal;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminarLocal;
    private javax.swing.JButton jButtonGenerarFactura;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabelBuscarCliente;
    private javax.swing.JLabel jLabelBuscarLocal;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelElegirTipoFactura;
    private javax.swing.JLabel jLabelFechaFactura;
    private javax.swing.JLabel jLabelIVA;
    private javax.swing.JLabel jLabelIVAValor;
    private javax.swing.JLabel jLabelPrecioUnitario;
    private javax.swing.JLabel jLabelPrecioUnitarioValor;
    private javax.swing.JLabel jLabelRetencion;
    private javax.swing.JLabel jLabelRetencionValor;
    private javax.swing.JLabel jLabelSeleccionarLocal;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanelBotonAgregarLocal;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelCuerpo;
    private javax.swing.JPanel jPanelDetallesFactura;
    private javax.swing.JPanel jPanelLabelTotal;
    private javax.swing.JPanel jPanelPiePagina;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelRadioButtons;
    private javax.swing.JPanel jPanelSeleccionarLocal;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JRadioButton jRadioButtonFactura;
    private javax.swing.JRadioButton jRadioButtonFacturaAbono;
    private javax.swing.JScrollPane jScrollPaneTabla;
    private javax.swing.JSpinner jSpinnerCantidad;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextFieldBuscadorClientes;
    private javax.swing.JTextField jTextFieldBuscadorLocales;
    // End of variables declaration//GEN-END:variables
}
