/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.ujaen.tfg.vistas;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import es.ujaen.tfg.controlador.UsuarioControlador;
import es.ujaen.tfg.modelo.Usuario;
import es.ujaen.tfg.utils.Utils;
import static es.ujaen.tfg.utils.Utils.ERROR_CONTRASENA;
import static es.ujaen.tfg.utils.Utils.ERROR_CONTRASENA_REPETIDA;
import static es.ujaen.tfg.utils.Utils.MENSAJE_CONTRASENA_CAMBIADA;
import static es.ujaen.tfg.utils.Utils.MENSAJE_CONTRASENA_IGUAL;
import static es.ujaen.tfg.utils.Utils.TITULO_CONTRASENA_CAMBIADA;
import static es.ujaen.tfg.utils.Utils.TITULO_CONTRASENA_IGUAL;
import static es.ujaen.tfg.utils.Utils.VALIDACION_CONTRASENA;
import static es.ujaen.tfg.utils.Utils.validarCampoFormulario;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author jota
 */
public class VistaCambiarContrasena extends javax.swing.JFrame {

    private final Usuario usuarioModificado;
    private final Usuario usuarioOriginal;

    private final UsuarioControlador usuarioControlador;
    
    private boolean campoContrasenaCorrecto;
    private boolean campoRepetirCorrecto;

    private boolean contrasenaVisible = false;

    private final Border originalBorder;
    
    private final JFrame parent;

    /**
     * Creates new form VistaRecuperarContrasena
     * @param parent
     * @param usuario
     * @param usuarioControlador
     */
    public VistaCambiarContrasena(JFrame parent, Usuario usuario, UsuarioControlador usuarioControlador) {
        initComponents();
        setLocationRelativeTo(null);

        this.parent = parent;
        
        ImageIcon icon = new ImageIcon("iconoFondoTransparente.png"); // Ruta de la imagen
        this.setIconImage(icon.getImage()); // Establecer el icono

        this.jPanelPrincipal.setBorder(new EmptyBorder(10, 10, 10, 10));
        
        this.originalBorder = jPasswordFieldNueva.getBorder();

        this.campoContrasenaCorrecto = false;
        this.campoRepetirCorrecto = false;

        this.contrasenaVisible = false;

        this.jLabelAdvertenciaNueva.setText(ERROR_CONTRASENA);
        this.usuarioControlador = usuarioControlador;
        
        this.usuarioModificado = new Usuario(usuario);
        this.usuarioOriginal = new Usuario(usuario);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelPrincipal = new javax.swing.JPanel();
        jPanelCabecera = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelCuerpo = new javax.swing.JPanel();
        jLabelNuevaContrasena = new javax.swing.JLabel();
        jPasswordFieldNueva = new javax.swing.JPasswordField();
        jLabelAdvertenciaNueva = new javax.swing.JLabel();
        jLabelRepetirContrasena = new javax.swing.JLabel();
        jPasswordFieldRepetir = new javax.swing.JPasswordField();
        jLabelAdvertenciaRepetir = new javax.swing.JLabel();
        jButtonMostrarContrasena = new javax.swing.JButton();
        jPanelPiePagina = new javax.swing.JPanel();
        jButtonCambiarContrasena = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Recuperar contraseña");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelPrincipal.setLayout(new java.awt.BorderLayout());

        jPanelCabecera.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitulo.setText("Modificar Contraseña");
        jPanelCabecera.add(jLabelTitulo);

        jPanelPrincipal.add(jPanelCabecera, java.awt.BorderLayout.PAGE_START);

        jPanelCuerpo.setLayout(new java.awt.GridBagLayout());

        jLabelNuevaContrasena.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNuevaContrasena.setText("Nueva Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelCuerpo.add(jLabelNuevaContrasena, gridBagConstraints);

        jPasswordFieldNueva.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPasswordFieldNueva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordFieldNuevaKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelCuerpo.add(jPasswordFieldNueva, gridBagConstraints);

        jLabelAdvertenciaNueva.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelAdvertenciaNueva.setForeground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelCuerpo.add(jLabelAdvertenciaNueva, gridBagConstraints);

        jLabelRepetirContrasena.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelRepetirContrasena.setText("Repetir Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelCuerpo.add(jLabelRepetirContrasena, gridBagConstraints);

        jPasswordFieldRepetir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPasswordFieldRepetir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordFieldRepetirKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelCuerpo.add(jPasswordFieldRepetir, gridBagConstraints);

        jLabelAdvertenciaRepetir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelAdvertenciaRepetir.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelCuerpo.add(jLabelAdvertenciaRepetir, gridBagConstraints);

        jButtonMostrarContrasena.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonMostrarContrasena.setIcon(new FlatSVGIcon("svg/ojo_cerrado.svg"));
        jButtonMostrarContrasena.setText("Mostrar Contraseña");
        jButtonMostrarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarContrasenaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelCuerpo.add(jButtonMostrarContrasena, gridBagConstraints);

        jPanelPrincipal.add(jPanelCuerpo, java.awt.BorderLayout.CENTER);

        jPanelPiePagina.setName(""); // NOI18N
        jPanelPiePagina.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonCambiarContrasena.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonCambiarContrasena.setText("Cambiar Contraseña");
        jButtonCambiarContrasena.setEnabled(false);
        jButtonCambiarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambiarContrasenaActionPerformed(evt);
            }
        });
        jPanelPiePagina.add(jButtonCambiarContrasena);

        jPanelPrincipal.add(jPanelPiePagina, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMostrarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarContrasenaActionPerformed
        // TODO add your handling code here:
        if (contrasenaVisible) {
            jPasswordFieldRepetir.setEchoChar('•'); // Ocultar contraseña
            jPasswordFieldNueva.setEchoChar('•'); // Ocultar contraseña
            jButtonMostrarContrasena.setIcon(new FlatSVGIcon("svg/ojo_cerrado.svg"));
        } else {
            jPasswordFieldRepetir.setEchoChar((char) 0); // Mostrar contraseña
            jPasswordFieldNueva.setEchoChar((char) 0); // Mostrar contraseña
            jButtonMostrarContrasena.setIcon(new FlatSVGIcon("svg/ojo.svg"));
        }
        contrasenaVisible = !contrasenaVisible;
    }//GEN-LAST:event_jButtonMostrarContrasenaActionPerformed

    private void jButtonCambiarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambiarContrasenaActionPerformed
        // TODO add your handling code here:
        String nuevaContrasena = new String(jPasswordFieldNueva.getPassword()).trim();

        String antiguaContrasenaHash = usuarioOriginal.getContrasena();
        String nuevaContrasenaHash = Usuario.hashContrasena(nuevaContrasena);
        
        if (!antiguaContrasenaHash.equals(nuevaContrasenaHash)) {

            usuarioModificado.setContrasenaHash(nuevaContrasena);

            usuarioControlador.actualizar(usuarioOriginal, usuarioModificado);

            Utils.mostrarInformacion(this, TITULO_CONTRASENA_CAMBIADA, MENSAJE_CONTRASENA_CAMBIADA);

            dispose();
            parent.setEnabled(true);
        } else {
            Utils.mostrarAdvertencia(this, TITULO_CONTRASENA_IGUAL, MENSAJE_CONTRASENA_IGUAL);
        }

    }//GEN-LAST:event_jButtonCambiarContrasenaActionPerformed

    private void jPasswordFieldNuevaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldNuevaKeyReleased
        // TODO add your handling code here:
        String pss = new String(jPasswordFieldNueva.getPassword());
        JTextField jTextFieldPassword = new JTextField(pss);
        JLabel jLabel = new JLabel();

        campoContrasenaCorrecto = validarCampoFormulario(
                jTextFieldPassword,
                jLabel,
                ERROR_CONTRASENA,
                originalBorder,
                texto -> !texto.isEmpty() && texto.matches(VALIDACION_CONTRASENA)
        );
        habilitarBotonCambiarContrasena();
    }//GEN-LAST:event_jPasswordFieldNuevaKeyReleased

    private void jPasswordFieldRepetirKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldRepetirKeyReleased
        // TODO add your handling code here:
        String pss = new String(jPasswordFieldNueva.getPassword());
        String pssRepetida = new String(jPasswordFieldRepetir.getPassword());

        if (!pss.equals(pssRepetida)) {
            jLabelAdvertenciaRepetir.setText(ERROR_CONTRASENA_REPETIDA);
            campoRepetirCorrecto = false;
        } else {
            jLabelAdvertenciaRepetir.setText("");
            campoRepetirCorrecto = true;
        }

        habilitarBotonCambiarContrasena();
    }//GEN-LAST:event_jPasswordFieldRepetirKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        parent.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        parent.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void habilitarBotonCambiarContrasena() {
        if (campoRepetirCorrecto) {
            if (campoContrasenaCorrecto) {
                jButtonCambiarContrasena.setEnabled(true);
                return;
            }
        }
        jButtonCambiarContrasena.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCambiarContrasena;
    private javax.swing.JButton jButtonMostrarContrasena;
    private javax.swing.JLabel jLabelAdvertenciaNueva;
    private javax.swing.JLabel jLabelAdvertenciaRepetir;
    private javax.swing.JLabel jLabelNuevaContrasena;
    private javax.swing.JLabel jLabelRepetirContrasena;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelCabecera;
    private javax.swing.JPanel jPanelCuerpo;
    private javax.swing.JPanel jPanelPiePagina;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPasswordField jPasswordFieldNueva;
    private javax.swing.JPasswordField jPasswordFieldRepetir;
    // End of variables declaration//GEN-END:variables
}
