/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package es.ujaen.tfg.vistas;

import java.awt.Component;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;

/**
 *
 * @author jota
 */
public class VistaContabilidad extends javax.swing.JPanel {

    /**
     * Creates new form VistaContabilidad
     */
    public VistaContabilidad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelCabecera = new javax.swing.JPanel();
        jPanelTitulo = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelFiltro = new javax.swing.JPanel();
        jLabelAnio = new javax.swing.JLabel();
        jSpinnerAnio = new javax.swing.JSpinner();
        jPanelCuerpo = new javax.swing.JPanel();
        jScrollPaneTabla = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanelCabecera.setToolTipText("");
        jPanelCabecera.setName(""); // NOI18N
        jPanelCabecera.setPreferredSize(new java.awt.Dimension(676, 74));
        jPanelCabecera.setLayout(new java.awt.GridLayout(2, 1));

        jPanelTitulo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelTitulo.setText("Contabilidad Mensual");
        jPanelTitulo.add(jLabelTitulo);

        jPanelCabecera.add(jPanelTitulo);

        jPanelFiltro.setLayout(new java.awt.GridBagLayout());

        jLabelAnio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelAnio.setText("Año Seleccionado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelFiltro.add(jLabelAnio, gridBagConstraints);

        jSpinnerAnio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jSpinnerAnio.setModel(new javax.swing.SpinnerNumberModel(2024, null, null, 1));
        jSpinnerAnio.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinnerAnio, "####"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 25.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelFiltro.add(jSpinnerAnio, gridBagConstraints);

        jPanelCabecera.add(jPanelFiltro);

        add(jPanelCabecera, java.awt.BorderLayout.PAGE_START);

        jPanelCuerpo.setLayout(new javax.swing.BoxLayout(jPanelCuerpo, javax.swing.BoxLayout.Y_AXIS));

        jTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cliente", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPaneTabla.setViewportView(jTable);
        if (jTable.getColumnModel().getColumnCount() > 0) {
            jTable.getColumnModel().getColumn(0).setPreferredWidth(200);
            jTable.getColumnModel().getColumn(1).setResizable(false);
            jTable.getColumnModel().getColumn(2).setResizable(false);
            jTable.getColumnModel().getColumn(3).setResizable(false);
            jTable.getColumnModel().getColumn(4).setResizable(false);
            jTable.getColumnModel().getColumn(5).setResizable(false);
            jTable.getColumnModel().getColumn(6).setResizable(false);
            jTable.getColumnModel().getColumn(7).setResizable(false);
            jTable.getColumnModel().getColumn(8).setResizable(false);
            jTable.getColumnModel().getColumn(9).setResizable(false);
            jTable.getColumnModel().getColumn(10).setResizable(false);
            jTable.getColumnModel().getColumn(11).setResizable(false);
            jTable.getColumnModel().getColumn(12).setResizable(false);
        }

        jPanelCuerpo.add(jScrollPaneTabla);

        add(jPanelCuerpo, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        // TODO add your handling code here:
        int row = jTable.rowAtPoint(evt.getPoint());
        int column = jTable.columnAtPoint(evt.getPoint());

        // Solo actuar si se clickea en columnas de meses (ignorar "Cliente")
        if (column > 0) {
            showPopupPanel(evt.getComponent(), evt.getX(), evt.getY(), row, column);
        }
    }//GEN-LAST:event_jTableMouseClicked

    private void showPopupPanel(Component parent, int x, int y, int row, int column) {
        // Crear el popup
        JPopupMenu popupMenu = new JPopupMenu();
        JPanel panel = new JPanel(new GridLayout(2, 1)); // Panel con 2 filas para los checkboxes

        JCheckBox pagadoCheckBox = new JCheckBox("Pagado");
        JCheckBox facturadoCheckBox = new JCheckBox("Facturado");

        // Obtener valor actual de la celda para preseleccionar valores
        Object cellValue = jTable.getValueAt(row, column);
        String value = cellValue != null ? cellValue.toString() : "";

        if (value.contains("Pagado")) {
            pagadoCheckBox.setSelected(true);
        }
        if (value.contains("Facturado")) {
            facturadoCheckBox.setSelected(true);
        }

        // Agregar checkboxes al panel
        panel.add(pagadoCheckBox);
        panel.add(facturadoCheckBox);

        // Agregar el panel al popup
        popupMenu.add(panel);

        // Añadir un botón para cerrar y guardar los cambios
        JButton guardarBtn = new JButton("Guardar");
        guardarBtn.addActionListener(e -> {
            // Lógica para actualizar la celda
            boolean pagado = pagadoCheckBox.isSelected();
            boolean facturado = facturadoCheckBox.isSelected();
            String newValue;

            if (pagado && facturado) {
                newValue = "Verde";
            } else if (!pagado && facturado) {
                newValue = "Rojo";
            } else if (pagado && !facturado) {
                newValue = "Amarillo";
            } else {
                newValue = "";
            }

            // Actualizar el valor en la tabla
            jTable.setValueAt(newValue, row, column);

            // Cerrar el popup
            popupMenu.setVisible(false);
        });

        // Añadir botón al popup
        popupMenu.add(guardarBtn);

        // Mostrar el popup en las coordenadas del clic
        popupMenu.show(parent, x, y);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAnio;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelCabecera;
    private javax.swing.JPanel jPanelCuerpo;
    private javax.swing.JPanel jPanelFiltro;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JScrollPane jScrollPaneTabla;
    private javax.swing.JSpinner jSpinnerAnio;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
