/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package es.ujaen.tfg.vistas;

import es.ujaen.tfg.controlador.PreferenciasControlador;
import es.ujaen.tfg.modelo.Preferencias;

/**
 *
 * @author jota
 */
public class VistaPreferencias extends javax.swing.JDialog {

    private final PreferenciasControlador preferenciasControlador;
    
    /**
     * Creates new form VistaPreferencias
     * @param parent
     * @param modal
     * @param preferenciasControlador
     */
    public VistaPreferencias(java.awt.Frame parent, boolean modal, PreferenciasControlador preferenciasControlador) {
        super(parent, modal);
        initComponents();
        this.preferenciasControlador = preferenciasControlador;
        setLocationRelativeTo(null);
        cargarPreferencias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelPrincipal = new javax.swing.JPanel();
        jPanelCabecera = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelCuerpo = new javax.swing.JPanel();
        jLabelIVA = new javax.swing.JLabel();
        jSpinnerIVA = new javax.swing.JSpinner();
        jLabelRetencion = new javax.swing.JLabel();
        jSpinnerRetencion = new javax.swing.JSpinner();
        jCheckBoxFacturasContiguas = new javax.swing.JCheckBox();
        jPanelPiePagina2 = new javax.swing.JPanel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Preferencias");
        setName("VistaPreferencias"); // NOI18N
        setSize(new java.awt.Dimension(348, 245));

        jPanelPrincipal.setLayout(new java.awt.BorderLayout());

        jPanelCabecera.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitulo.setText("Preferencias");
        jPanelCabecera.add(jLabelTitulo);

        jPanelPrincipal.add(jPanelCabecera, java.awt.BorderLayout.PAGE_START);

        jPanelCuerpo.setLayout(new java.awt.GridBagLayout());

        jLabelIVA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelIVA.setText("IVA por Defecto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelCuerpo.add(jLabelIVA, gridBagConstraints);

        jSpinnerIVA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jSpinnerIVA.setModel(new javax.swing.SpinnerNumberModel(21, 0, 100, 1));
        jSpinnerIVA.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinnerIVA, "0 '%'"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelCuerpo.add(jSpinnerIVA, gridBagConstraints);

        jLabelRetencion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelRetencion.setText("Retencion Por Defecto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelCuerpo.add(jLabelRetencion, gridBagConstraints);

        jSpinnerRetencion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jSpinnerRetencion.setModel(new javax.swing.SpinnerNumberModel(19, 0, 100, 1));
        jSpinnerRetencion.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinnerRetencion, "0 '%'"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelCuerpo.add(jSpinnerRetencion, gridBagConstraints);

        jCheckBoxFacturasContiguas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBoxFacturasContiguas.setText("Facturas Contiguas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelCuerpo.add(jCheckBoxFacturasContiguas, gridBagConstraints);

        jPanelPrincipal.add(jPanelCuerpo, java.awt.BorderLayout.CENTER);

        jPanelPiePagina2.setName(""); // NOI18N
        jPanelPiePagina2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanelPiePagina2.add(jButtonCancelar);

        jButtonAceptar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        jPanelPiePagina2.add(jButtonAceptar);

        jPanelPrincipal.add(jPanelPiePagina2, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:
        guardarPreferencias();
        dispose();
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    /**
     * Carga las preferencias desde el controlador y las muestra en la vista.
     */
    private void cargarPreferencias() {
        Preferencias preferencias = preferenciasControlador.obtenerPreferencias();
        jSpinnerIVA.setValue(preferencias.getIva());
        jSpinnerRetencion.setValue(preferencias.getRetencion());
        jCheckBoxFacturasContiguas.setSelected(preferencias.getFacturasContiguas());
    }
    
    /**
     * Recoge los valores de la vista y los envía al controlador.
     */
    private void guardarPreferencias() {
        Preferencias nuevasPreferencias = new Preferencias(
                (Integer) jSpinnerIVA.getValue(),
                (Integer) jSpinnerRetencion.getValue(),
                (Boolean) jCheckBoxFacturasContiguas.isSelected()
        );
        preferenciasControlador.guardarPreferencias(nuevasPreferencias);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JCheckBox jCheckBoxFacturasContiguas;
    private javax.swing.JLabel jLabelIVA;
    private javax.swing.JLabel jLabelRetencion;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelCabecera;
    private javax.swing.JPanel jPanelCuerpo;
    private javax.swing.JPanel jPanelPiePagina2;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JSpinner jSpinnerIVA;
    private javax.swing.JSpinner jSpinnerRetencion;
    // End of variables declaration//GEN-END:variables
}
